### ISSUE TITLE
Is there anyway to sort a pair?

### ISSUE THREAD

**Issue by mrdotrue** [ips4o/ips2ra#3]
Hi, I am interested in integrating this project to my own project. But I need to sort a pair which only the first element need to be sorted. Is there anyway to do that? Great thanks!

**Comment by ips4o** [comment]
Do you want to bring the first values of the pairs into sorted order but the actual pair (which includes the second value) shall not be moved? This might be a little bit tricky.

If you want the pairs sorted with the first value as the key, you can simply use this code
```
  ips2ra::sort(v.begin(), v.end(), [](const auto& e) {return e.first;});
```

**Comment by mrdotrue** [comment]
Great thanks!
